config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/auth/:provider/callback' => 'users/sessions#omniauth'
  #get '/user' => "test#index", :as => :user_root

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #{sessions: 'sessions'} if override sessions is used
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_out', to: 'users/sessions#delete', as: :destroy_user_session
  end

  get 'home', to: 'home#index'

  get '/upload', to: 'pdf_processor#upload', as: 'upload'
  post 'pdf_processor/process_pdf'

  #post 'pdf_processor/csv'
  get 'pdf_processor/csv', to: 'pdf_processor#csv', as: :pdf_processor_csv
  get 'pdf_processor/batch', to: 'pdf_processor#batch'
  post 'pdf_processor/process_batch', to: 'pdf_processor#process_batch'



  get '/show' , to: 'member_view#show' , as: 'show'

  resources :training_enrollments do
    member do
      get :delete
    end

    collection do
      get :user_enrollments
    end
    post :email_all, on: :collection
    post :send_emails, on: :collection
    post :update_email_frequency, on: :collection

  end
  resources :users do
    member do
      get :delete
    end


  end

  get 'training_courses/csv', to: 'training_courses#csv', as: :training_course_csv
  resources :training_courses
  #get 'training_courses/csv', to: 'training_courses#csv', as: :training_courses_csv

  # Route for projects index page
  get '/projects', to: 'projects#index', as: 'projects_index'
  get '/projects/:project_id/edit', to: 'projects#edit', as: 'edit_project'
  patch '/projects/:project_id', to: 'projects#update'
  resources :projects, only: [:show, :new, :create, :destroy], param: :project_id do
    member do
      get :delete
      get :delete_confirm
      get '/projects/:project_id/delete_confirm', to: 'projects#delete_confirm', as: 'delete_project_confirm'
      get :add_member, to: 'projects#_add_member_form'
      post :create_member
      delete :remove_member
      get :remove_member_confirmation, to: 'projects#remove_member'
      post :create_record
      post :accept_member
      post :reject_member
      #post :export_workday_attendance
      #get :csv, to: 'project#csv', as: :project_csv
      get :add_many_members, to: 'projects#add_many_members'
      post :create_many_members
      get :remove_many_members, to: 'projects#remove_many_members'
      post :destroy_many_members
    end
  end
  get 'projects/:project_id/csv', to: 'projects#csv', as: :project_workday_csv
  

  resources :scheduled_workdays, only: [:create]



  get '/manage_members', to: 'manage_members#index', as: 'manage_members'
  get '/manage_members/new', to: 'manage_members#new', as: 'new_manage_member'
  get '/manage_members/batch', to: 'manage_members#process_batch', as: 'manage_members_process_batch'
post '/manage_members/batch', to: 'manage_members#process_batch'
  resources :manage_members, only: [:index, :new, :create, :destroy] do
    post :update_role

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/faq', to: 'faq#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/training_courses_controller.rb
# frozen_string_literal: true

class TrainingCoursesController < ApplicationController
  before_action :set_training_course, only: %i[show edit update destroy]

  # GET /training_courses or /training_courses.json
  def index
    @training_courses = TrainingCourse.all
  end

  # GET /training_courses/1 or /training_courses/1.json
  def show; end

  # GET /training_courses/new
  def new
    @training_course = TrainingCourse.new
  end

  # GET /training_courses/1/edit
  def edit; end

  # POST /training_courses or /training_courses.json
  def create
    @training_course = TrainingCourse.new(training_course_params)

    respond_to do |format|
      if @training_course.save
        format.html { redirect_to }
        format.json { render(:show, status: :created, location: @training_course) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @training_course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /training_courses/1 or /training_courses/1.json
  def update
    respond_to do |format|
      if @training_course.update(training_course_params)
        format.html { redirect_to(training_courses_path, notice: 'Training course was successfully updated.') }
        format.json { render(:show, status: :ok, location: @training_course) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @training_course.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /training_courses/1 or /training_courses/1.json
  def destroy
    @training_course.destroy!

    respond_to do |format|
      format.html { redirect_to(training_courses_path) }
      format.json { head(:no_content) }
    end
  end

  
  def csv 
    respond_to do |format|
      format.html
      format.csv { send_data TrainingCourse.to_csv(%w(full_name)), filename: "all-user-training-status-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
    end
  end 

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_training_course
    @training_course = TrainingCourse.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def training_course_params
    params.require(:training_course).permit(:name, :course_id)
  end

end

app/helpers/training_courses_helper.rb
# frozen_string_literal: true

module TrainingCoursesHelper
end

app/views/training_courses/_form.html.erb
<%= form_with(model: training_course) do |form| %>
  <% if training_course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(training_course.errors.count, "error") %> prohibited this training_course from being saved:</h2>

      <ul>
        <% training_course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Course Name" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :course_id, "Course ID" %>
    <%= form.number_field :course_id, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-custom mr-2" %>
  </div>
<% end %>

app/views/training_courses/_training_course.html.erb
<div id="<%= dom_id training_course %>">
</div>

app/views/training_courses/edit.html.erb
<div class="container mt-5">
  <h1 class="text-center">Edit Training Course</h1>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= render "form", training_course: @training_course %>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= link_to "Back to Training Courses", training_courses_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/training_courses/index.html.erb
<p class="text-success"><%= notice %></p>

<div class="container mt-5">
  <h1>Required Training Courses</h1>
  <div>
  <%= link_to "New Training Course", new_training_course_path, class: "btn btn-custom", style: "margin-bottom: 10px;" %>
  <%= link_to "Back to Admin View", training_enrollments_path, class: "btn btn-custom", style: "margin-bottom: 10px;" %>
</div>

  <div class="row">
    <% @training_courses.each do |training_course| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title text-center"><%= training_course.name %></h5>
            <p class="card-text">Course ID: <%= training_course.course_id %></p>
            <!-- Add more details here if needed -->
            <div class="text-center">
              <div class="btn-group" role="group">
                <%= link_to "Edit", edit_training_course_path(training_course), class: "btn btn-custom mr-2" , style: "margin-right: 5px;"%> 
                <%= form_tag(training_course_path(training_course), method: :delete) do %>
                  <%= submit_tag "Delete", class: "btn btn-custom mr-2" %>
                <% end %>
              </div>


            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  

</div>

app/views/training_courses/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">New Training Course</h1>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= render "form", training_course: @training_course %>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= link_to "Back to Training Courses", training_courses_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/training_courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @training_course %>

<div>
  <%= link_to "Edit this training course", edit_training_course_path(@training_course) %> |
  <%= link_to "Back to training courses", training_courses_path %>

  <%= button_to "Destroy this training course", @training_course, method: :delete %>
</div>