config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/auth/:provider/callback' => 'users/sessions#omniauth'
  #get '/user' => "test#index", :as => :user_root

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #{sessions: 'sessions'} if override sessions is used
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_out', to: 'users/sessions#delete', as: :destroy_user_session
  end

  get 'home', to: 'home#index'

  get '/upload', to: 'pdf_processor#upload', as: 'upload'
  post 'pdf_processor/process_pdf'

  #post 'pdf_processor/csv'
  get 'pdf_processor/csv', to: 'pdf_processor#csv', as: :pdf_processor_csv
  get 'pdf_processor/batch', to: 'pdf_processor#batch'
  post 'pdf_processor/process_batch', to: 'pdf_processor#process_batch'



  get '/show' , to: 'member_view#show' , as: 'show'

  resources :training_enrollments do
    member do
      get :delete
    end

    collection do
      get :user_enrollments
    end
    post :email_all, on: :collection
    post :send_emails, on: :collection
    post :update_email_frequency, on: :collection

  end
  resources :users do
    member do
      get :delete
    end


  end

  get 'training_courses/csv', to: 'training_courses#csv', as: :training_course_csv
  resources :training_courses
  #get 'training_courses/csv', to: 'training_courses#csv', as: :training_courses_csv

  # Route for projects index page
  get '/projects', to: 'projects#index', as: 'projects_index'
  get '/projects/:project_id/edit', to: 'projects#edit', as: 'edit_project'
  patch '/projects/:project_id', to: 'projects#update'
  resources :projects, only: [:show, :new, :create, :destroy], param: :project_id do
    member do
      get :delete
      get :delete_confirm
      get '/projects/:project_id/delete_confirm', to: 'projects#delete_confirm', as: 'delete_project_confirm'
      get :add_member, to: 'projects#_add_member_form'
      post :create_member
      delete :remove_member
      get :remove_member_confirmation, to: 'projects#remove_member'
      post :create_record
      post :accept_member
      post :reject_member
      #post :export_workday_attendance
      #get :csv, to: 'project#csv', as: :project_csv
      get :add_many_members, to: 'projects#add_many_members'
      post :create_many_members
      get :remove_many_members, to: 'projects#remove_many_members'
      post :destroy_many_members
    end
  end
  get 'projects/:project_id/csv', to: 'projects#csv', as: :project_workday_csv
  

  resources :scheduled_workdays, only: [:create]



  get '/manage_members', to: 'manage_members#index', as: 'manage_members'
  get '/manage_members/new', to: 'manage_members#new', as: 'new_manage_member'
  get '/manage_members/batch', to: 'manage_members#process_batch', as: 'manage_members_process_batch'
post '/manage_members/batch', to: 'manage_members#process_batch'
  resources :manage_members, only: [:index, :new, :create, :destroy] do
    post :update_role

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/faq', to: 'faq#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/training_enrollment.rb
# frozen_string_literal: true

class TrainingEnrollment < ApplicationRecord
  # has_many :users
  # has_one :training_course
  #belongs_to :training_course

  require 'csv'

  def self.to_csv(train_attributes = column_names, name_attribute = training_courses.column_names, id = passed_id, options = {})
    CSV.generate do |csv|
      csv << train_attributes + name_attribute
      where(user_id: id).each do |training|
        values = training.attributes.slice(*train_attributes).values

        if training.course_id
          training_course = TrainingCourse.find_by(course_id: training.course_id)
          values += training_course.attributes.slice(*name_attribute).values
        end

        csv << values
      end
    end
  end
end

app/controllers/training_enrollments_controller.rb
# frozen_string_literal: true

class TrainingEnrollmentsController < ApplicationController
  def index
    @enrollments = TrainingEnrollment.all
    @valid_results = @enrollments.map { |enrollment| check_validity(enrollment) }
  end

  def show
    @enrollment = TrainingEnrollment.find(params[:id])
    @valid_result = check_validity(@enrollment)
  end

  def new
    @enrollment = TrainingEnrollment.new
  end

  def create
    @enrollment = TrainingEnrollment.new(enrollment_params)
    if @enrollment.save
      redirect_to(training_enrollment_path(@enrollment))
    else
      # assign instance variables needed
      Rails.logger.debug(@enrollment.errors.full_messages)
      render('new')
    end
  end

  def edit
    @enrollment = TrainingEnrollment.find_by(id: params[:id])
  end

  def update
    @enrollment = TrainingEnrollment.find_by(id: params[:id])
    if @enrollment.update(enrollment_params)
      redirect_to(training_enrollment_path)
    else
      render('edit')
    end
  end

  def delete
    @enrollment = TrainingEnrollment.find(params[:id])
  end

  def destroy
    @enrollment = TrainingEnrollment.find(params[:id])
    @enrollment.destroy!
    # render('index')
    redirect_to(training_enrollments_path)
  end

  def user_enrollments
    @user = User.find_by(uid: params[:user_id].to_s)
    @enrollments = []

    TrainingCourse.all.find_each do |course|
      result = TrainingService.check_enrollment_and_validity(course, @user)
      enrollment = {}
      enrollment[:course_title] = course.name
      enrollment[:course_id] = course.course_id
      enrollment[:result] = result
      @enrollments << enrollment
    end

    # Respond to HTML format request
    respond_to do |format|
      format.html
    end
  end

  def email_all
    # Render the confirmation view
    render 'email_all_confirmation'
  end

  def send_emails
    # Call the function from TrainingService
    TrainingService.send_emails_for_overdue_trainings

    # Redirect or render as needed
    redirect_to training_enrollments_path, notice: 'Custom action performed successfully.'
  end

  def update_email_frequency
    # Your code to update email frequency goes here
    # For example, you might fetch the params and update the email frequency setting
    new_frequency = params[:email_frequency]
    ENV['EMAIL_FREQUENCY'] = new_frequency
    puts "SET TO #{ENV['EMAIL_FREQUENCY']}"

    # Redirect or render as needed
    redirect_to training_enrollments_path, notice: 'Email frequency updated successfully.'
  end

  private

  def check_validity(enrollment)
    TrainingService.check_validity(enrollment)
  end

  def enrollment_params
    params.require(:training_enrollment).permit(:course_id, :user_id, :completion_status)
  end

  # checks if the training is expired (1 year old)
  def out_of_date?(enrollment)
    if enrollment.completion_status.present?
      completion_status_threshold = 1.year.ago
      return enrollment.completion_status < completion_status_threshold
    end

    false
  end

  def almost_out_of_date?(enrollment)
    if enrollment.completion_status.present?
      completion_status_threshold = 11.months.ago
      return enrollment.completion_status < completion_status_threshold
    end

    false
  end

end

app/helpers/training_enrollments_helper.rb
# frozen_string_literal: true

module TrainingEnrollmentsHelper
end

app/views/training_enrollments/_form.html.erb
<table class="table table-bordered" summary="Training Enrollment form fields">
  <tr>
    <th>Course ID</th>
    <td><%= f.text_field(:course_id, class: 'form-control') %></td>
  </tr>
  <tr>
    <th>User ID</th>
    <td><%= f.text_field(:user_id, class: 'form-control') %></td>
  </tr>
  <tr>
    <th>Completion Date</th>
    <td><%= f.date_field(:completion_status, class: 'form-control') %></td>
  </tr>
</table>

app/views/training_enrollments/delete.html.erb
<div class="container">
  <h2>Delete Training Enrollment</h2>

  <%= link_to("Back to all Enrollments", training_enrollments_path, class: 'btn btn-secondary back-link') %>

  <%= form_for(@enrollment, method: 'delete') do |f| %>
    <% # url: task_path(@task), method: 'delete' %>

    <p>Are you sure you want to permanently delete this enrollment?</p>
    <p><%= @enrollment.course_id %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Enrollment", class: 'btn btn-danger') %>
    </div>
  <% end %>
</div>

app/views/training_enrollments/edit.html.erb
<div class="container">
  <h2>Edit Enrollment</h2>

  <%= link_to("Back to List", training_enrollments_path, class: 'btn btn-secondary back-link') %>

  <%= form_for(@enrollment) do |f| %>
    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Edit Enrollment", class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/training_enrollments/email_all_confirmation.html.erb
<!-- app/views/training_enrollments/email_all_confirmation.html.erb -->
<div class="container mt-4">
  <h1 class="mb-4">Confirmation</h1>
  <p>Are you sure you want to email all students who have invalid training?</p>
  <%= form_tag send_emails_training_enrollments_path, method: :post, class: "mt-3" do %>
    <%= submit_tag "Confirm", class: "btn btn-custom mr-2" %>
    <%= link_to "Cancel", training_enrollments_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/training_enrollments/email_manager.html.erb

<h1>Email Manager</h1>

<%= form_with(url: training_enrollments_path, method: :post) do |form| %>
  <div class="field">
    <%= form.label :input_field, "Input Field" %>
    <%= form.text_field :input_field %>
  </div>

  <%= form.submit "Submit" %>
<% end %>

<% if @emailcontent.present? %>
  <p>Entered content: <%= @emailcontent %></p>
<% end %>

app/views/training_enrollments/index.html.erb
<div class="container">
  <h2 class="mb-4">Training Enrollments</h2>

  <%= link_to "Course Manager", training_courses_path, class: "btn btn-custom mb-1" %>
  <%= link_to "Export Training Status as CSV", training_course_csv_path(format: 'csv'), class: "btn btn-custom mb-1" %>

  <!-- Email All Button -->
  <%= form_tag({ controller: 'training_enrollments', action: 'email_all' }, method: 'post') do %>
    <div class="email-button-container">
      <%= button_tag('Email all', class: 'btn btn-custom', type: 'submit') %>
      <p class="email-button-text">This emails all students who have invalid training.</p>
    </div>
  <% end %>

  <p>The following shows all of the members in your organization and their training status. Click on their name to see detailed info on their training status.</p>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>User</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% User.all.sort_by { |user| user.full_name.split.last }.each do |user| %>
          <% overall_status = "Valid" %>
          <% TrainingCourse.all.each do |course| %>
            <% enrollment_result = TrainingService.check_enrollment_and_validity(course, user) %>
            <% if enrollment_result != "Valid" && enrollment_result != "Expiring Soon!" %>
              <% overall_status = "Invalid" %>
              <% break %>
            <% end %>
          <% end %>
          <tr>
            <td>
              <% first_name, *rest_of_name = user.full_name.split %>
              <% last_name = rest_of_name.pop %>
              <% middle_name = rest_of_name.join(' ') if rest_of_name.any? %>
              <% if middle_name.present? %>
                <%= link_to "#{last_name}, #{first_name} #{middle_name}", user_enrollments_training_enrollments_path(user_id: user.uid), class: overall_status == "Valid" ? "text-success" : "text-danger" %>
              <% else %>
                <%= link_to "#{last_name}, #{first_name}", user_enrollments_training_enrollments_path(user_id: user.uid), class: overall_status == "Valid" ? "text-success" : "text-danger" %>
              <% end %>
            </td>
            <td><%= overall_status %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/training_enrollments/new.html.erb
<div class="container">
  <h2>Create Enrollment</h2>

  <%= form_for(@enrollment) do |f| %>
    <%= render(partial: 'form', locals: { f: f }) %>

    <div class="form-buttons">
      <%= f.submit("Create Enrollment", class: 'btn btn-primary') %>
    </div>
  <% end %>
</div>

app/views/training_enrollments/show.html.erb
<div class="container">
  <h2>Show Enrollment</h2>

  <div class="actions">
    <%= link_to('Back to List', training_enrollments_path, class: 'btn btn-secondary back-link') %>
    <%= link_to('Edit', edit_training_enrollment_path(@enrollment), class: 'btn btn-primary') %>
    <%= link_to('Delete', delete_training_enrollment_path(@enrollment), class: 'btn btn-danger') %>
  </div>

  <table class="table table-bordered" summary="Task detail view">
    <tr>
      <th>Course ID</th>
      <td><%= @enrollment.course_id %></td>
    </tr>
    <tr>
      <th>User ID</th>
      <td><%= @enrollment.user_id %></td>
    </tr>
    <tr>
      <th>Completion Status</th>
      <td><%= @enrollment.completion_status %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @enrollment.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @enrollment.updated_at %></td>
    </tr>
  </table>
</div>

app/views/training_enrollments/update.html.erb
<h1>TrainingEnrollments#update</h1>
<p>Find me in app/views/training_enrollments/update.html.erb</p>

app/views/training_enrollments/user_enrollments.html.erb
<!-- app/views/training_enrollments/user_enrollments.html.erb -->
<div class="container">
  <div class="card">
    <div class="card-body">
      <h3 class="card-title">Training Status for <%= @user.full_name %></h3>
      <table class="table">
        <thead>
          <tr>
            <th>Course</th>
            <th>Completion Status</th>
          </tr>
        </thead>
        <tbody>
          <% @enrollments.each do |enrollment| %>
            <tr>
              <td><%= enrollment[:course_title] %> - <%= enrollment[:course_id] %></td>
              <td><%= enrollment[:result] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="card-footer">
      <%= link_to "Back to All Students", training_enrollments_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>