config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/auth/:provider/callback' => 'users/sessions#omniauth'
  #get '/user' => "test#index", :as => :user_root

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #{sessions: 'sessions'} if override sessions is used
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_out', to: 'users/sessions#delete', as: :destroy_user_session
  end

  get 'home', to: 'home#index'

  get '/upload', to: 'pdf_processor#upload', as: 'upload'
  post 'pdf_processor/process_pdf'

  #post 'pdf_processor/csv'
  get 'pdf_processor/csv', to: 'pdf_processor#csv', as: :pdf_processor_csv
  get 'pdf_processor/batch', to: 'pdf_processor#batch'
  post 'pdf_processor/process_batch', to: 'pdf_processor#process_batch'



  get '/show' , to: 'member_view#show' , as: 'show'

  resources :training_enrollments do
    member do
      get :delete
    end

    collection do
      get :user_enrollments
    end
    post :email_all, on: :collection
    post :send_emails, on: :collection
    post :update_email_frequency, on: :collection

  end
  resources :users do
    member do
      get :delete
    end


  end

  get 'training_courses/csv', to: 'training_courses#csv', as: :training_course_csv
  resources :training_courses
  #get 'training_courses/csv', to: 'training_courses#csv', as: :training_courses_csv

  # Route for projects index page
  get '/projects', to: 'projects#index', as: 'projects_index'
  get '/projects/:project_id/edit', to: 'projects#edit', as: 'edit_project'
  patch '/projects/:project_id', to: 'projects#update'
  resources :projects, only: [:show, :new, :create, :destroy], param: :project_id do
    member do
      get :delete
      get :delete_confirm
      get '/projects/:project_id/delete_confirm', to: 'projects#delete_confirm', as: 'delete_project_confirm'
      get :add_member, to: 'projects#_add_member_form'
      post :create_member
      delete :remove_member
      get :remove_member_confirmation, to: 'projects#remove_member'
      post :create_record
      post :accept_member
      post :reject_member
      #post :export_workday_attendance
      #get :csv, to: 'project#csv', as: :project_csv
      get :add_many_members, to: 'projects#add_many_members'
      post :create_many_members
      get :remove_many_members, to: 'projects#remove_many_members'
      post :destroy_many_members
    end
  end
  get 'projects/:project_id/csv', to: 'projects#csv', as: :project_workday_csv
  

  resources :scheduled_workdays, only: [:create]



  get '/manage_members', to: 'manage_members#index', as: 'manage_members'
  get '/manage_members/new', to: 'manage_members#new', as: 'new_manage_member'
  get '/manage_members/batch', to: 'manage_members#process_batch', as: 'manage_members_process_batch'
post '/manage_members/batch', to: 'manage_members#process_batch'
  resources :manage_members, only: [:index, :new, :create, :destroy] do
    post :update_role

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/faq', to: 'faq#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/manage_members_controller.rb
# frozen_string_literal: true

require 'csv'

class ManageMembersController < ApplicationController
  def index
    @users = User.all.order(:full_name)
  end

  def new
    @user = User.new
  end

  def create
    if User.exists?(email: user_params[:email])
      redirect_to manage_members_path(alert: 'A user with this email already exists!.')
    else
      @user = User.new(user_params)
      @user.full_name = user_params[:email]
      @user.uid = generate_uid
      @user.avatar_url = 'testing'
      if @user.save
        if params[:user][:project_ids].present?
          params[:user][:project_ids].each do |project_id|
            project = Project.find_by(id: project_id)
            if project
              ProjectMember.create(project_id: project.project_id, user_id: @user.uid)
            end
          end
        end
        redirect_to manage_members_path, notice: 'New member added successfully.'
      else
        render(:new)
      end
    end
  end

  before_action :authenticate_user!, only: [:destroy]
  def destroy
    @member = User.find_by(uid: params[:id])
    if @member.destroy
      ProjectMember.where(user_id: @member.uid).destroy_all
      redirect_to(manage_members_path, notice: 'Member removed successfully.')
    else
      redirect_to(manage_members_path, alert: 'Failed to remove member.')
    end
  end

  def update_role
    updatee = User.where(uid: params[:uid])
    updatee.update!(role: params[:role])
    redirect_to(manage_members_path)
  end

  def process_batch
    csv_file = params[:csv_file]
    emails_added = []

    if csv_file.present? && csv_file.content_type == 'text/csv'
      csv_data = csv_file.read
      csv = CSV.parse(csv_data, headers: true)

      csv.each do |row|
        email = row['email']
        name = email
        next unless valid_tamu_email?(email)
        next if User.find_by(email: email)

        user = User.new(email: email, full_name: name, uid: generate_uid, role: 'Member')
        if user.save
          emails_added << email
          Rails.logger.debug { "User #{email} added to the database." }
        else
          Rails.logger.debug { "Error creating user #{email}: #{user.errors.full_messages.join(', ')}" }
        end
      end

      flash[:success] = "#{emails_added.count} valid emails added to the database."
    else
      flash.now[:error] = 'Please upload a valid CSV file.'
    end

    render(:batch)
  end

  private

  def user_params
    params.require(:user).permit(:email, :role, :full_name)
  end

  def generate_uid
    # Logic to generate the UID, such as finding the highest current uid and incrementing it
    highest_uid = Integer((User.maximum(:uid) || '0'), 10)
    (highest_uid + 1).to_s
  end

  def valid_tamu_email?(email)
    email.present? && email =~ URI::MailTo::EMAIL_REGEXP && email.ends_with?('@tamu.edu')
  end
end

app/helpers/manage_members_helper.rb
# frozen_string_literal: true

module ManageMembersHelper
end

app/views/manage_members/batch.html.erb
<div class="container">
  <h1 class="mt-5">Upload Multiple Members</h1>
  <%= link_to "Back to Manage Members", manage_members_path, class: "btn btn-custom", style: "margin-bottom: 10px;" %>
  <p>Upload a CSV containing the emails of the members you would like to add. The emails must be valid TAMU addresses ending in @tamu.edu. The CSV should contain one column of emails with the header 'email' (For info on CSV's see the help section) </p>
  <%= form_tag manage_members_process_batch_path, multipart: true, class: "mt-3" do %>
    <div class="form-group">
      <%= label_tag :csv_file, "CSV File", class: "form-label" %>
      <%= file_field_tag :csv_file, class: "form-control-file" %>
    </div>

    <%= submit_tag "Upload", class: "btn btn-custom mt-3" %>
  <% end %>

  <% if flash[:success] %>
    <div class="alert alert-success mt-3">
      <%= flash[:success] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger mt-3">
      <%= flash[:error] %>
    </div>
  <% end %>

  <% if defined?(@emails) && !@emails.empty? %>
    <h2>Extracted Emails:</h2>
    <ul>
      <% emails.each do |email| %>
        <li><%= email %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/manage_members/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Manage Members</h1>
  <div class="mb-3">
    <%= link_to "New Member", new_manage_member_path, class: "btn btn-custom" %>
    <%= link_to "Batch Upload", manage_members_process_batch_path,class: "btn btn-custom"%>

  </div>
  <div class="table-responsive">
    <table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Remove</th>
    </tr>
  </thead>
<tbody>
  <% @users.sort_by { |user| user.full_name.split.last }.each do |member| %>
    <tr>
      <td>
        <% first_name, *rest_of_name = member.full_name.split %>
        <% last_name = rest_of_name.pop %>
        <% middle_name = rest_of_name.join(' ') if rest_of_name.any? %>
        <% if middle_name.present? %>
          <%= "#{last_name}, #{first_name} #{middle_name}" %>
        <% else %>
          <%= "#{last_name}, #{first_name}" %>
        <% end %>
      </td>
      <td><%= member.email %></td>
      <td>
        <form action="<%= manage_member_update_role_path(member.uid) %>" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div class="input-group">
            <select name="role" class="form-select">
              <option value="Admin" <%= 'selected' if member.role == 'Admin' %>>Admin</option>
              <option value="Member" <%= 'selected' if member.role == 'Member' %>>Member</option>
            </select>
            <input type="hidden" name="uid" value="<%= member.uid %>">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </form>
      </td>
      <td>
        <%= button_to "Remove", manage_member_path(member.uid), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</tbody>

</table>

  </div>
</div>

app/views/manage_members/new.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Add New Member</h1>

  <%= form_with(model: @user, url: manage_members_path, method: :post) do |form| %>
    
    <%= form.hidden_field :full_name, value: "Default Name" %>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :role %>
      <%= form.select :role, ["Member", "Admin"], {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :projects, "Team Membership", class: 'fw-bold' %><br>
      <% Project.all.each do |project| %>
        <div class="form-check">
          <%= form.check_box :project_ids, { multiple: true }, project.project_id, nil %>
          <%= form.label :project_ids, project.project_name, class: 'form-check-label' %>
        </div>
      <% end %>
    </div>

    <%= form.submit "Add Member", class: "btn btn-primary" %>
    <%= link_to "Cancel", manage_members_path, class: 'btn btn-secondary' %>
  <% end %>
</div>