config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/auth/:provider/callback' => 'users/sessions#omniauth'
  #get '/user' => "test#index", :as => :user_root

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } #{sessions: 'sessions'} if override sessions is used
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    post 'users/sign_out', to: 'users/sessions#delete', as: :destroy_user_session
  end

  get 'home', to: 'home#index'

  get '/upload', to: 'pdf_processor#upload', as: 'upload'
  post 'pdf_processor/process_pdf'

  #post 'pdf_processor/csv'
  get 'pdf_processor/csv', to: 'pdf_processor#csv', as: :pdf_processor_csv
  get 'pdf_processor/batch', to: 'pdf_processor#batch'
  post 'pdf_processor/process_batch', to: 'pdf_processor#process_batch'



  get '/show' , to: 'member_view#show' , as: 'show'

  resources :training_enrollments do
    member do
      get :delete
    end

    collection do
      get :user_enrollments
    end
    post :email_all, on: :collection
    post :send_emails, on: :collection
    post :update_email_frequency, on: :collection

  end
  resources :users do
    member do
      get :delete
    end


  end

  get 'training_courses/csv', to: 'training_courses#csv', as: :training_course_csv
  resources :training_courses
  #get 'training_courses/csv', to: 'training_courses#csv', as: :training_courses_csv

  # Route for projects index page
  get '/projects', to: 'projects#index', as: 'projects_index'
  get '/projects/:project_id/edit', to: 'projects#edit', as: 'edit_project'
  patch '/projects/:project_id', to: 'projects#update'
  resources :projects, only: [:show, :new, :create, :destroy], param: :project_id do
    member do
      get :delete
      get :delete_confirm
      get '/projects/:project_id/delete_confirm', to: 'projects#delete_confirm', as: 'delete_project_confirm'
      get :add_member, to: 'projects#_add_member_form'
      post :create_member
      delete :remove_member
      get :remove_member_confirmation, to: 'projects#remove_member'
      post :create_record
      post :accept_member
      post :reject_member
      #post :export_workday_attendance
      #get :csv, to: 'project#csv', as: :project_csv
      get :add_many_members, to: 'projects#add_many_members'
      post :create_many_members
      get :remove_many_members, to: 'projects#remove_many_members'
      post :destroy_many_members
    end
  end
  get 'projects/:project_id/csv', to: 'projects#csv', as: :project_workday_csv
  

  resources :scheduled_workdays, only: [:create]



  get '/manage_members', to: 'manage_members#index', as: 'manage_members'
  get '/manage_members/new', to: 'manage_members#new', as: 'new_manage_member'
  get '/manage_members/batch', to: 'manage_members#process_batch', as: 'manage_members_process_batch'
post '/manage_members/batch', to: 'manage_members#process_batch'
  resources :manage_members, only: [:index, :new, :create, :destroy] do
    post :update_role

  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get '/faq', to: 'faq#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :project_members, dependent: :destroy
  has_one_attached :project_photo
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def show

    @project = Project.find_by(project_id: params[:project_id])
    @upcoming_workdays = ScheduledWorkday.where('day >= ? AND project_id = ?', Time.zone.today, @project.project_id)
    @previous_workdays = ScheduledWorkday.where('day < ? AND project_id = ?', Time.zone.today, @project.project_id)
    @pending_members = AttendanceRecord.where('checkin >= ? AND project_id = ?', Time.zone.today, @project.project_id)
    @approval_status = AttendanceRecord.where('user_id = ? AND checkin >= ? AND project_id = ?', current_user.uid, Time.zone.today,
                                              @project.project_id
    )
    @previous_status = AttendanceRecord.where('user_id = ? AND checkin < ? AND project_id = ?', current_user.uid, Time.zone.today,
                                              @project.project_id
    )

    @status = if AttendanceRecord.where('project_id = ? AND user_id = ?', @project.project_id, current_user.uid)
                AttendanceRecord.find_by(user_id: current_user.uid, project_id: @project.project_id)
              else
                false
              end

    if current_user.uid == @project.leader_id
      @scheduled_workday = ScheduledWorkday.new
      render('show_leader')
    else
      render('show_member')
    end
  end

  def index
    @projects = Project.all.order(:project_id)
  end

  # rubocop:disable Lint/NumberConversion
  def new
    @project = Project.new
    @project.project_id = Project.maximum(:project_id).to_i + 1
  end
  # rubocop:enable Lint/NumberConversion

  def create
    @project = Project.new(project_params)
    @project.id = @project.project_id
    if @project.save
      ProjectMember.create(project_id: @project.id, user_id: @project.leader_id)
      @project.update!(project_id: @project.id)
      redirect_to(project_path(@project), notice: 'Team was successfully created.')
    else
      render(:new)
    end
  end

  def destroy
    @project = Project.find_by(project_id: params[:project_id])
    if @project.destroy
      redirect_to(projects_index_path, notice: 'Team was successfully deleted.')
    else
      redirect_to(project_path(@project), alert: 'Failed to delete the project.')
    end
  end

  def delete_confirm
    @project = Project.find(params[:project_id])
  end

  def delete
    @project = Project.find(params[:project_id])
  end

  def add_member
    @project = Project.find_by(project_id: params[:project_id])
    @project_member = @project.project_members.build
  end

  def create_member
    @project = Project.find_by(project_id: params[:project_id])
    user_id = params[:user_id]

    if ProjectMember.exists?(project_id: @project.project_id, user_id: user_id)
      redirect_to project_path(@project, anchor: 'members-tab-pane'), alert: 'This user is already a member of the project.'
    else
      @project_member = @project.project_members.build(user_id: user_id)

      if @project_member.save
        redirect_to project_path(@project, anchor: 'members-tab-pane'), notice: 'Member was successfully added to the project.'
      else
        redirect_to project_path(@project, anchor: 'members-tab-pane'), alert: 'Failed to add member to the project.'
      end
    end
  end

  def add_many_members
    @project = Project.find(params[:project_id])
    @project_member = ProjectMember.new
    @users = User.all.sort_by { |user| user.full_name.split.last }
    render 'add_many_members'
  end

  def create_many_members
    @project = Project.find(params[:project_id])
    user_ids = params[:user_ids]

    if user_ids.present?
      user_ids.each do |user_id|
        if ProjectMember.exists?(project_id: @project.id, user_id: user_id)
          flash[:alert] = 'One or more selected users are already members of the team.'
          redirect_to add_many_members_project_path(@project)
          return  # Return to exit the action after redirect
        else
          @project.project_members.create(user_id: user_id)
        end
      end
      redirect_to project_path(@project, anchor: 'members-tab-pane'), notice: 'Selected members were successfully added to the team.'
    else
      redirect_to project_path(@project, anchor: 'members-tab-pane'), alert: 'No members selected.'
    end
  end

  def remove_many_members
    @project = Project.find(params[:project_id])
    @project_members = ProjectMember.where(project_id: @project.project_id)
    @users = @project_members.map { |project_member| User.find_by(uid: project_member.user_id) }.compact
    @users.sort_by! { |user| user.full_name.split.last.downcase }
  end

  def destroy_many_members
    @project = Project.find(params[:project_id])
    user_ids = params[:user_ids]

    if user_ids.present?
      user_ids.each do |user_id|
        project_member = ProjectMember.find_by(project_id: @project.project_id, user_id: user_id)
        project_member.destroy if project_member
      end
      flash[:notice] = 'Selected members were removed from the team.'
    else
      flash[:alert] = 'No members selected for removal.'
    end

    redirect_to project_path(@project, anchor: 'members-tab-pane')
  end

  def remove_member_confirmation
    @member = User.find_by(uid: params[:member_id])
    render(:remove_member)
  end

  def remove_member
    @project = Project.find_by(project_id: params[:project_id])
    @member = User.find_by(uid: params[:member_id])
    @project_member = @project.project_members.find_by(user_id: @member.uid)

    if @project_member.destroy
      flash[:notice] = 'Member removed from the team successfully.'
    else
      flash[:error] = 'Failed to remove member from the team.'
    end
    redirect_to project_path(@project, anchor: 'members-tab-pane')
  end

  def create_record
    workday = ScheduledWorkday.find(params[:workday_id])
    @project = Project.find(params[:project_id])
    if AttendanceRecord.create!(user_id: current_user.uid, schedule_id: workday.id, project_id: workday.project_id,
                                checkin: Time.current.in_time_zone('Central Time (US & Canada)'), approval_status: false
    )

      redirect_to(project_path(@project, anchor: 'upcoming-tab-pane'), notice: 'Checked in successfully.')
    else
      render(:index)
    end
  end

  def accept_member
    checkin = AttendanceRecord.where(user_id: params[:user_id], schedule_id: params[:schedule_id])
    @project = Project.find(params[:project_id])
    if checkin&.update!(approval_status: true)
      redirect_to(project_path(@project, anchor: 'upcoming-tab-pane'), notice: 'Accepted Check in.')
    else
      redirect_to(project_path(@project, anchor: 'upcoming-tab-pane'), alert: 'Failed to Accept Check in.')
    end
  end

  def reject_member
    reject_checkin = AttendanceRecord.where(user_id: params[:user_id], schedule_id: params[:schedule_id]).first
    @project = Project.find(params[:project_id])
    if reject_checkin.destroy!
      redirect_to(project_path(@project, anchor: 'upcoming-tab-pane'), notice: 'Rejected Check in.')
    else
      redirect_to(project_path(@project, anchor: 'upcoming-tab-pane'), alert: 'Failed to Reject Check in.')
    end
  end

  def edit
    @project = Project.find_by(project_id: params[:project_id])
  end

  def update
    @project = Project.find_by(project_id: params[:project_id])
    if @project.update(project_params)
      redirect_to(project_path(@project), notice: 'Team was successfully updated.')
    else
      render(:edit)
    end
  end

  def csv
    project = Project.find(params[:project_id])
    scheduled_workday = ScheduledWorkday.find(params[:schedule_id])
    respond_to do |format|
      format.html
      format.csv { send_data AttendanceRecord.to_csv(%w(approval_status), %w(full_name), project.project_id, scheduled_workday.id), filename: "workday#{project.project_name}-day#{scheduled_workday.day}-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
    end
  end

  private

  def project_params
    params.require(:project).permit(:project_name, :leader_id, :project_id, :project_photo, :other_attributes)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_add_members_form.html.erb
<div class="d-flex justify-content-left">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Add Team Member</h3>
        <%= link_to "Add Multiple Members", add_many_members_project_path(@project), class: "btn btn-primary mt-3" %>
        <%= form_with(model: @project_member, url: create_member_project_path(@project), method: :post) do |form| %>
          <div class="form-group">
            <%= form.label :user_id, class: 'fw-bold' %>
            <%= form.select :user_id, User.all.sort_by { |user| user.full_name.split.last }.map { |user| [user.full_name, user.uid] }, {}, { class: 'form-control' } %>
          </div>
          <%= form.hidden_field :project_id, value: @project.project_id %>
          <%= form.submit "Add One Member", class: "btn btn-primary mt-3" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-12 pl-8">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Current Team Members</h3>
        <ul class="list-group">
        <%= link_to "Remove Multiple Members", remove_many_members_project_path(@project), class: "btn btn-danger mt-3" %>
        <% ProjectMember.where(project_id: @project.project_id).map { |pm| User.find_by(uid: pm.user_id) }.compact.sort_by { |user| user.full_name.split.last }.each do |user| %>
            <% if user %>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                <%= user.full_name %> 
                <%= link_to "Remove", remove_member_confirmation_project_path(@project, member_id: user.uid), class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to remove this member from the project?" } %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/projects/add_many_members.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Add Multiple Members to Team</h1>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Select Members to Add</h3>
          <div class="member-list">
            <%= form_tag(create_many_members_project_path(@project), method: :post) do %>
              <% @users.each do |user| %>
                <div class="form-check">
                  <%= check_box_tag "user_ids[]", user.uid, false, class: 'form-check-input' %>
                  <%= label_tag "user_#{user.uid}", user.full_name, class: 'form-check-label' %>
                </div>
              <% end %>
              <%= hidden_field_tag :project_id, @project.id %>
              <%= submit_tag "Add Selected Members", class: "btn btn-primary mt-3" %>
              <%= link_to "Cancel", project_path(@project, anchor: 'members-tab-pane'), class: "btn btn-secondary mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/add_member.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Project Member</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <div class="container">
    <h1>Add Project Member</h1>
    <%= form_with(model: @project_member, url: create_member_project_path(@project), method: :post, local: true) do |form| %>
      <div class="form-group">
        <h3><%= form.label :user_id %></h3>
        <%= form.select :user_id, User.all.map { |user| [user.full_name, user.uid] }, {}, { class: 'form-control' } %>
      </div>
      
      <%= hidden_field_tag :project_id, @project.id %>
    
      <%= form.submit "Add Member", class: 'btn btn-primary' %>
      <%= link_to "Cancel", edit_project_path(@project), class: 'btn btn-secondary' %>
    <% end %>
        
  </div>
</body>
</html>

app/views/projects/delete.html.erb
<!-- delete.html.erb -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Delete Project</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container">
  <%= form_for(@project, method: 'delete') do |f| %>
    <h1>Delete Project: <%= @project.project_name %></h1>
    <p>Are you sure you want to delete this project?</p>
    <%= f.submit "Delete Project", class: "btn btn-danger" %>
    <%= link_to "Cancel", projects_path, class: "btn btn-secondary" %>
  <% end %>

</div>

</body>
</html>

app/views/projects/index.html.erb
<head>
  <style>
    .card-img-top {
      height: 200px;
      object-fit: cover;
    }
    .card {
      transition: transform 0.3s ease;
    }
    .card:hover {
      transform: translateY(-5px);
      box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }
    /* Additional styles for buttons */
    .project-buttons {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
  </style>
</head>
<body>
    <div class="container">
    <h1>Current Teams</h1>
    <%= link_to 'Create Team', new_project_path, class: "btn btn-primary btn-block mb-3" %>

    <div class="row">
        <% @projects.each do |project| %>
        <div class="col-md-4 mb-4">
            <div class="card">
            <div class="card-body">
                <h5 class="card-title"><%= project.project_name %></h5>
                <p class="card-text">Team Manager: <% user = User.find_by(uid: project.leader_id) %>
                <% if user %>
                <li><%= user.full_name %></li>
                <% else %>
                <li>Team Manager Not Found</li>
                <% end %></p>
                <p class="card-text">Total Members: <%= ProjectMember.count_for_project(project.project_id) %></p>
                <%= link_to "", project_path(project.project_id), id: project.project_id, class: "stretched-link" %>
            </div>
            
            </div>
        </div>
        <% end %>
    </div>
    </div>
</body>

app/views/projects/remove_many_members.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Remove Multiple Members from Project</h1>

  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Select Members to Remove</h3>
          <div class="member-list">
            <%= form_tag(destroy_many_members_project_path(@project), method: :post) do %>
              <% @users.each do |user| %>
                <div class="form-check">
                  <%= check_box_tag "user_ids[]", user.uid, false, class: 'form-check-input' %>
                  <%= label_tag "user_#{user.uid}", user.full_name, class: 'form-check-label' %>
                </div>
              <% end %>
              <%= hidden_field_tag :project_id, @project.id %>
              <%= submit_tag "Remove Selected Members", class: "btn btn-danger mt-3" %>
              <%= link_to "Cancel", project_path(@project, anchor: 'members-tab-pane'), class: "btn btn-secondary mt-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/remove_member.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>Confirmation</title>
</head>
<body>
    <div class="container">
        <h2>Are you sure you want to remove this member from the project?</h2>
        <h3>Member: <%= @member.id %></h3>
        <%= link_to "Remove Member", remove_member_project_path(@project, member_id: @member.id), method: :delete, class: "btn btn-danger" %>
        <%= link_to "Cancel", edit_project_path(@project), class: "btn btn-secondary" %>
    </div>
</body>
</html>

app/views/projects/show_leader.html.erb
<h1><%= @project.project_name %></h1>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-15">
      <% if User.find_by(uid: current_user.uid).role == 'Admin' %>
        <div class="d-flex justify-content-end">
          <%= button_to "Edit Team", edit_project_path(@project), method: :get, class: "btn btn-primary mr-2 w-500", title: "Edit Project" %>
          <%= button_to "Delete Team", delete_project_confirm_project_path(@project), method: :get, class: "btn btn-danger mr-2 w-500", title: "Delete Project" %>
        </div>
      <% end %>
    </div>
  </div>
  <ul class="nav nav-tabs" id="workdaysTabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link" href="#create-tab-pane">Create Workdays</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#upcoming-tab-pane">Upcoming Workdays</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#previous-tab-pane">Previous Workdays</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#members-tab-pane">Manage Members</a>
    </li>
  </ul>
  <div class="tab-content" id="workdaysTabsContent">
    <div class="tab-pane" id="create-tab-pane" role="tabpanel">
      <div class="row mt-3">
        <%= form_with(model: @scheduled_workday, url: scheduled_workdays_path, method: :post) do |form| %>
          <%= form.hidden_field :program_manager_id, value: current_user.uid %>
          <%= form.hidden_field :project_id, value: @project.project_id %>
          <div class="form-group">
            <%= form.label :day %>
            <%= form.date_field :day, class: "form-control" %>
          </div>
          <br>
          <%= form.submit "Create Scheduled Workday", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="tab-pane" id="upcoming-tab-pane" role="tabpanel">
      <div class="row mt-3">
        <% @upcoming_workdays.each do |workday| %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Pending Status For Members</h5>
                <p class="card-text">Date: <%= workday.day %></p>
              <% (@pending_members.where(schedule_id: workday.id)).each do |member| %>
                <% if member.approval_status == false %>
                  <li>
                  <%= User.find_by(uid: member.user_id).full_name %> 
                  <%= form_with(url: accept_member_project_path(@project), method: :post, local: true) do |form| %>
                    <%= form.hidden_field :schedule_id, value:  workday.id %>
                    <%= form.hidden_field :user_id, value:  member.user_id %>
                    <%= form.submit "Accept", class: "btn btn-primary mr-2 mt-2" %>
                  <% end %>
                  <%= form_with(url: reject_member_project_path(@project), method: :post, local: true) do |form| %>
                    <%= form.hidden_field :schedule_id, value:  workday.id %>
                    <%= form.hidden_field :user_id, value:  member.user_id %>
                    <%= form.submit "Reject", class: "btn btn-primary" %>
                  <% end %>
                  </li>
                <% end %>
              <% end %>
              <h5 class="card-title">Approved Status For Members</h5>
              <% (@pending_members.where(schedule_id: workday.id)).each do |member| %>
                <% if member.approval_status %>
                  <li>
                  <%= User.find_by(uid: member.user_id).full_name %> 
                  </li>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="tab-pane" id="previous-tab-pane" role="tabpanel">
  <div class="row mt-3">
    <% @previous_workdays.each do |workday| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Previous Workday</h5>
            <p class="card-text">Date: <%= workday.day %></p>
                <%= form_tag(project_workday_csv_path(format: 'csv'), method: :get) do %>
                  <%= hidden_field_tag :project_id, @project.project_id %>
                  <%= hidden_field_tag :schedule_id, workday.id %>
                  <%= submit_tag "Export Workday Attendance", class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane" id="members-tab-pane" role="tabpanel">
      <div class="row mt-3">
        <div class="col-md-6">
          <%= render 'add_members_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/show_member.html.erb
<h1><%= @project.project_name %></h1>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-15">
      <% if User.find_by(uid: current_user.uid).role == 'Admin' %>
        <div class="d-flex justify-content-end">
          <%= button_to "Edit Team", edit_project_path(@project), method: :get, class: "btn btn-primary mr-2 w-500", title: "Edit Project" %>
          <%= button_to "Delete Team", delete_project_confirm_project_path(@project), method: :get, class: "btn btn-danger mr-2 w-500", title: "Delete Project" %>
      </div>
      <% end %>
    </div>
  </div>
  <ul class="nav nav-tabs" id="workdaysTabs" role="tablist">
    <li class="nav-item">
      <a class="nav-link" href="#upcoming-tab-pane">Upcoming Workdays</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#previous-tab-pane">Previous Workdays</a>
    </li>
    <% if User.find_by(uid: current_user.uid).role == 'Admin' %>
    <li class="nav-item">
      <a class="nav-link" href="#members-tab-pane">Manage Members</a>
    </li>
    <% end %>
  </ul>
  <div class="tab-content" id="workdaysTabsContent">
    <div class="tab-pane fade show active" id="upcoming-tab-pane" role="tabpanel" aria-labelledby="upcoming-tab">
      <div class="row mt-3">
        <% @upcoming_workdays.each do |workday| %>
          <div class="col-md-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Upcoming Workday</h5>
                <p class="card-text">Date: <%= workday.day %></p>
                <% if ProjectMember.exists?(project_id: @project.project_id, user_id: current_user.uid) %>
                <% attendance_record = AttendanceRecord.find_by(user_id: current_user.uid, schedule_id: workday.id) %>
                  <% if attendance_record %>
                    <% if attendance_record.approval_status %>
                      <p class="card-text">Status: Approved</p>
                    <% else %>
                      <p class="card-text">Status: Pending Approval</p>
                    <% end %>
                    <%= form_with(url: create_record_project_path(@project), method: :post, local: true, html: { disabled: true }) do |form| %>
                      <%= form.hidden_field :workday_id, value: workday.id %>
                      <%= form.submit "Check In", class: "btn btn-primary", disabled: true %>
                    <% end %>
                  <% else %>
                    <p class="card-text">Status: Not Checked In</p>
                    <% if workday.day <= Time.zone.today %>
                      <%= form_with(url: create_record_project_path(@project), method: :post, local: true) do |form| %>
                        <%= form.hidden_field :workday_id, value: workday.id %>
                        <%= form.submit "Check In", class: "btn btn-primary" %>
                      <% end %>
                    <% else %>
                      <%= form_with(url: create_record_project_path(@project), method: :post, local: true, html: { disabled: true }) do |form| %>
                        <%= form.hidden_field :workday_id, value: workday.id %>
                        <%= form.submit "Check In", class: "btn btn-primary", disabled: true %>
                      <% end %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane" id="previous-tab-pane" role="tabpanel" aria-labelledby="previous-tab">
    <div class="row mt-3">
      <% @previous_workdays.each do |workday| %>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Previous Workday</h5>
              <p class="card-text">Date: <%= workday.day %></p>
              <% attendance_record = AttendanceRecord.find_by(user_id: current_user.uid, schedule_id: workday.id) %>
              <% if attendance_record %>
                <% if attendance_record.approval_status %>
                  <p class="card-text">Status: Approved</p>
                <% else %>
                  <p class="card-text">Status: Not Approved</p>
                <% end %>
              <% else %>
                <p class="card-text">Status: Not Approved</p>
              <% end %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
    </div>
    <% if User.find_by(uid: current_user.uid).role == 'Admin' %>
    <div class="tab-pane" id="members-tab-pane" role="tabpanel">
      <div class="row mt-3">
        <div class="col-md-6">
          <%= render 'add_members_form' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>